modLoader = "javafml"
loaderVersion = "[45,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/Pale-Champion-Atom596/TRAPPIST-1/issues"

[[mods]]
modId = "ad_trappist"
version = "${version}"
displayName = "Ad Trappist"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/modid"
logoFile = "icon.png"
authors = "Atom596"
credits = "AlexNijjar's Template Mod"
description = "Addon for Ad Astra including the 7 planets of the TRAPPIST-1 system "

[[dependencies.ad_trappist]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_trappist]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_trappist]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_trappist]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[${resourcefulconfig_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_trappist]]
modId = "botarium"
mandatory = true
versionRange = "[${botarium_version},)"
ordering = "NONE"
side = "BOTH"